### ISSUE TITLE
[todo] 2024-02-19 까지 마무리 해야 하는 할 일

### ISSUE THREAD

**Issue by Ujaa** [sookmyung-graduation-project-2023/lipread#1]
[중요한 할 일]
- [x] 학습 플로우에 맞게 기능 추가
- [ ] 학습 완료 다이알로그/학습 완료 버튼 마무리

[버그]
- [ ] 1. 홈에서 tabview 내부 item wrap 하는 형태로 변경
- [ ] 2. bronova 폰트 적용 안되는 버그 해결
- [ ] 3. 학습 중 백링크 없애기
- [ ] 4. 학습 메세지 문장 생성 후 밑줄 없애기

[기타 할 일]
- [ ] 1. 이미지 위치 애뮬레이터가 아니라 핸드폰에서 정상적인지 확인
- [ ] 2. 맞춤형 없을 때 empty data 추가

[refactoring]
- [ ] 공통 values 분리해서 정리
- [ ] api endpoint 분리해서 정리
- [ ] sharedpreferences -> provider로 정리
- [ ] token 관리 효율적으로 변경

** 반응형 values로 변경(시간 남으면)
