### ISSUE TITLE
[todo] 2021-02-22까지 할 일

### ISSUE THREAD

**Issue by Ujaa** [sookmyung-graduation-project-2023/lipread#3]
- [x] 1. 아이콘 4개 만들기
- [x] #4
- [x] #5
- [x] 4. 맞춤법 검사 후 보여주기 UI 완성
- [x] 5. 학습 통계 계산 후 학습 마무리 과정 완성
- [x] 6. 학습 기록 페이지 API 연결
