### ISSUE TITLE
[todo] 2024-03-05 할 일

### ISSUE THREAD

**Issue by Ujaa** [sookmyung-graduation-project-2023/lipread#6]
- [ ] 최근 구화 불러오기 (만약 최근 구화가 없으면 해당 창 없애고 새로운 학습 페이지로 이동 (다이알로그나 toast 메세지로 알림)
- [ ] provider로 입력한 내용 저장하기
- [ ] 키보드 올라올 때 floating button bottom margin 너무 넓은 것 해결
